import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parsePatch,inspectPorts,listInstances,createPlan,applyPlan,sha256,validText,textFromBytes,validateMap,instanceKey,filename} from '../src/core.mjs';
const head='#N canvas 0 0 500 400 12;\n';
const oldModule={name:'triplet.pd',text:head+'#X obj 20 20 inlet;\n#X obj 120 20 inlet;\n#X obj 220 20 inlet;\n#X obj 20 200 outlet;\n#X obj 120 200 outlet;\n'};
const newModule={name:'revised.pd',text:head+'#X obj 220 20 inlet;\n#X obj 20 20 inlet;\n#X obj 120 20 inlet;\n#X obj 120 200 outlet;\n#X obj 20 200 outlet;\n'};
const caller={name:'caller.pd',text:head+'#X text 0 0 triplet \\; harmless \\, comment;\n#X obj 10 40 triplet;\n#X obj 100 40 triplet-extra;\n#X msg 0 80 7;\n#X obj 10 120 print;\n#X connect 3 0 1 0;\n#X connect 1 0 4 0;\n#X connect 2 0 4 0;\n'};
const args=()=>({oldModule:{...oldModule},newModule:{...newModule},callers:[{...caller}],inputMap:[2,0,1],outputMap:[1,0]});
const migrate=async(a=args())=>applyPlan({...a,plan:await createPlan(a)});
const err=(code)=>e=>e.code===code;
test('ports use physical left-to-right order, not record order',()=>assert.deepEqual(inspectPorts(newModule.text).inputs.map(p=>p.objectIndex),[1,2,0]));
test('text counts in object index; escaped separators stay within a record',()=>{const p=parsePatch(caller.text);assert.equal(p.root.objects.length,5);assert.equal(p.root.objects[1].className,'triplet');});
test('match only exact unqualified object class, never prefix/comments',()=>assert.deepEqual(listInstances(caller.text,'triplet').map(i=>i.index),[1]));
test('only endpoint integers change and order/whitespace remain',async()=>{const r=await migrate();assert.equal(r.files[1].text,caller.text.replace('#X connect 3 0 1 0;','#X connect 3 0 1 2;').replace('#X connect 1 0 4 0;','#X connect 1 1 4 0;'));assert.equal(r.receipt.changedTokens,2);});
test('new module exported under old exact basename',async()=>{const r=await migrate();assert.equal(r.files[0].name,'triplet.pd');assert.equal(r.files[0].text,newModule.text);});
test('identity mapping is byte-for-byte no-op',async()=>{const a=args();a.inputMap=[0,1,2];a.outputMap=[0,1];const r=await migrate(a);assert.equal(r.files[1].text,caller.text);assert.equal(r.receipt.changedTokens,0);});
test('CRLF and tabs survive',async()=>{const a=args();a.callers[0].text=caller.text.replaceAll('\n','\r\n').replace('#X connect 3 0 1 0;','#X\tconnect  3\t0 1\t0;');const r=await migrate(a);assert.equal(r.files[1].text,a.callers[0].text.replace('3\t0 1\t0;','3\t0 1\t2;').replace('1 0 4 0;','1 1 4 0;'));});
test('nested canvas indices are local, restore counts in parent',async()=>{const a=args();a.callers[0].text=head+'#X text 0 0 preface;\n#N canvas 0 0 300 300 inner 0;\n#X text 0 0 nested;\n#X obj 0 30 triplet;\n#X msg 0 60 5;\n#X connect 2 0 1 1;\n#X restore 0 50 pd inner;\n#X obj 0 100 triplet;\n#X msg 0 150 9;\n#X connect 3 0 2 2;\n';const p=parsePatch(a.callers[0].text);assert.equal(p.root.objects.length,4);assert.equal(p.canvases[1].id,'root/1');const r=await migrate(a);assert.equal(r.receipt.selectedInstances,2);assert.match(r.files[1].text,/#X connect 2 0 1 0;/);assert.match(r.files[1].text,/#X connect 3 0 2 1;/);});
test('explicit subset leaves other exact-name instances alone',async()=>{const a=args();a.callers[0].text=head+'#X obj 0 0 triplet;\n#X obj 0 30 triplet;\n#X connect 0 0 1 0;\n';a.selected=['caller.pd::root::0'];const r=await migrate(a);assert.match(r.files[1].text,/#X connect 0 1 1 0;/);});
test('selected-to-selected connection changes both endpoints',async()=>{const a=args();a.callers[0].text=head+'#X obj 0 0 triplet;\n#X obj 0 30 triplet;\n#X connect 0 0 1 0;\n';const r=await migrate(a);assert.match(r.files[1].text,/#X connect 0 1 1 2;/);assert.equal(r.receipt.changedTokens,2);});
test('double application is rejected by source binding',async()=>{const a=args(),plan=await createPlan(a),r=await applyPlan({...a,plan});await assert.rejects(applyPlan({...a,plan,callers:[r.files[1]]}),err('HASH'));});
test('changed caller source rejects a saved map',async()=>{const a=args(),plan=await createPlan(a);a.callers[0].text+='\n';await assert.rejects(applyPlan({...a,plan}),err('HASH'));});
test('changed old abstraction rejects a saved map',async()=>{const a=args(),plan=await createPlan(a);a.oldModule.text+='\n';await assert.rejects(applyPlan({...a,plan}),err('HASH'));});
test('changed revised abstraction rejects a saved map',async()=>{const a=args(),plan=await createPlan(a);a.newModule.text+='\n';await assert.rejects(applyPlan({...a,plan}),err('HASH'));});
test('receipt source/output hashes are computed from full bytes',async()=>{const r=await migrate();assert.equal(r.receipt.files[0].beforeSha256,await sha256(caller.text));assert.equal(r.receipt.files[0].afterSha256,await sha256(r.files[1].text));});
for(const map of [[0,0,2],[0,1],[0,1,3],[-1,1,2],[0,1,2.5],['0',1,2],null])test(`reject incomplete/nonbijective map ${JSON.stringify(map)}`,()=>assert.throws(()=>validateMap(map,3),err('MAP')));
test('equal-X inlet order rejected',()=>assert.throws(()=>inspectPorts(oldModule.text.replace('120 20 inlet','20 20 inlet')),err('AMBIGUOUS')));
test('equal-X outlet order rejected',()=>assert.throws(()=>inspectPorts(oldModule.text.replace('120 200 outlet','20 200 outlet')),err('AMBIGUOUS')));
test('signal ports rejected',()=>assert.throws(()=>inspectPorts(oldModule.text.replace('inlet;','inlet~;')),err('SIGNAL')));
test('typed/argument control ports rejected',()=>assert.throws(()=>inspectPorts(oldModule.text.replace('inlet;','inlet symbol;')),err('PORT')));
test('added port rejected',async()=>{const a=args();a.newModule.text+='#X obj 300 20 inlet;\n';await assert.rejects(createPlan(a),err('COUNT'));});
test('unknown record rejected',()=>assert.throws(()=>parsePatch(head+'#X mystery 2;\n'),err('RECORD')));
test('array data records rejected',()=>assert.throws(()=>parsePatch(head+'#A 0 1 2;\n'),err('RECORD')));
test('clone and declare rejected',()=>{for(const o of ['clone triplet 3','declare -path abc'])assert.throws(()=>parsePatch(head+`#X obj 0 0 ${o};\n`),err('UNSUPPORTED'));});
test('dynamic canvas message rejected',()=>assert.throws(()=>parsePatch(head+'#X msg 0 0 \\; pd-inner obj 1 2 triplet;\n'),err('UNSUPPORTED')));
test('unclosed child canvas rejected',()=>assert.throws(()=>parsePatch(head+'#N canvas 0 0 300 300 inner 0;\n'),err('CANVAS')));
test('orphan restore rejected',()=>assert.throws(()=>parsePatch(head+'#X restore 0 0 pd inner;\n'),err('CANVAS')));
test('mismatched child restore rejected',()=>assert.throws(()=>parsePatch(head+'#N canvas 0 0 300 300 inner 0;\n#X restore 0 0 pd other;\n'),err('CANVAS')));
test('out of range object index rejected',()=>assert.throws(()=>parsePatch(head+'#X obj 0 0 print;\n#X connect 1 0 0 0;\n'),err('INDEX')));
test('connections to comments rejected',()=>assert.throws(()=>parsePatch(head+'#X text 0 0 comment;\n#X obj 0 30 print;\n#X connect 0 0 1 0;\n'),err('INDEX')));
test('negative/fractional connection index rejected',()=>{for(const index of ['-1','0.5','Infinity','NaN'])assert.throws(()=>parsePatch(head+`#X obj 0 0 print;\n#X connect ${index} 0 0 0;\n`),err('INDEX'));});
test('selected input port out of range rejected',async()=>{const a=args();a.callers[0].text=caller.text.replace('3 0 1 0;','3 0 1 3;');await assert.rejects(migrate(a),err('INDEX'));});
test('selected output port out of range rejected',async()=>{const a=args();a.callers[0].text=caller.text.replace('1 0 4 0;','1 2 4 0;');await assert.rejects(migrate(a),err('INDEX'));});
test('zero input/output side allowed and validates empty bijection',()=>assert.deepEqual(inspectPorts(head+'#X obj 0 0 outlet;\n').inputs,[]));
test('multiple caller names must be portable unique',async()=>{const a=args();a.callers.push({...caller,name:'CALLER.pd'});await assert.rejects(createPlan(a),err('FILENAME'));});
test('caller cannot overwrite revised module',async()=>{const a=args();a.callers[0].name='triplet.pd';await assert.rejects(createPlan(a),err('FILENAME'));});
test('filenames reject path traversal and reserved names',()=>{for(const name of ['../a.pd','a/b.pd','a\\b.pd','nul.pd','.hidden.pd','a..b.pd'])assert.throws(()=>filename(name),err('FILENAME'));});
test('no valid selected instance rejected',async()=>{const a=args();a.selected=[];await assert.rejects(createPlan(a),err('SELECTION'));});
test('forged selected instance rejected',async()=>{const a=args(),plan=await createPlan(a);plan.callers[0].instances[0].index=2;await assert.rejects(applyPlan({...a,plan}),err('SELECTION'));});
test('duplicate selected instance rejected',async()=>{const a=args();a.selected=['caller.pd::root::1','caller.pd::root::1'];await assert.rejects(createPlan(a),err('SELECTION'));});
test('invalid UTF-8 rejected instead of silently replacing bytes',()=>assert.throws(()=>textFromBytes(new Uint8Array([255,254])),err('ENCODING')));
test('NUL, BOM and unpaired surrogates rejected',()=>{for(const v of ['\0','\uFEFF','\uD800'])assert.throws(()=>validText(head+v),err('ENCODING'));});
test('size bound enforced',()=>assert.throws(()=>validText('x'.repeat(524289)),err('LIMIT')));
test('optional object width metadata supported without being a port argument',()=>{const p=inspectPorts(oldModule.text.replace('inlet;','inlet, f 12;'));assert.equal(p.inputs.length,3);});
test('qualified and escaped target names are not silently resolved',()=>{for(const cls of ['./triplet','other/triplet'])assert.equal(listInstances(head+`#X obj 0 0 ${cls};\n`,'triplet').length,0);assert.throws(()=>listInstances(head+'#X obj 0 0 trip\\let;\n','triplet'),err('UNSUPPORTED'));});
test('string/object rendering never changes Unicode comment content',async()=>{const a=args();a.callers[0].text=caller.text.replace('harmless','日本語 🧵');const r=await migrate(a);assert.ok(r.files[1].text.includes('日本語 🧵'));});
test('non-ASCII whitespace cannot disguise a structural record',()=>assert.throws(()=>parsePatch(head.replace('#N canvas','#N\u00a0canvas')),err('RECORD')));
test('interface size is bounded before building option matrices',()=>assert.throws(()=>inspectPorts(head+Array.from({length:65},(_,i)=>`#X obj ${i*2} 0 inlet;\n`).join('')),err('LIMIT')));
test('matching instance count is bounded',async()=>{const a=args();a.callers[0].text=head+Array.from({length:513},()=>`#X obj 0 0 triplet;\n`).join('');await assert.rejects(createPlan(a),err('LIMIT'));});
test('connection count is bounded',async()=>{const a=args();a.callers[0].text=head+'#X obj 0 0 triplet;\n'+('#X connect 0 0 0 0;\n'.repeat(5001));await assert.rejects(createPlan(a),err('LIMIT'));});
test('saved contract rejects string instance indices instead of silently making no edits',async()=>{const a=args(),plan=await createPlan(a);plan.callers[0].instances[0].index='1';await assert.rejects(applyPlan({...a,plan}),err('SELECTION'));});
test('saved contract rejects malformed instance shapes explicitly',async()=>{for(const instance of [null,[],{}, {canvas:'root',index:-1},{canvas:'root',index:1.5},{canvas:null,index:1},{canvas:'root/01',index:1},{canvas:'root',index:NaN}]){const a=args(),plan=await createPlan(a);plan.callers[0].instances=[instance];await assert.rejects(applyPlan({...a,plan}),err('SELECTION'));}});
test('saved contract rejects malformed caller shapes explicitly',async()=>{for(const caller of [null,[],{}, {name:'caller.pd',sha256:'oops',instances:[]}]){const a=args(),plan=await createPlan(a);plan.callers=[caller];await assert.rejects(applyPlan({...a,plan}),err('PLAN'));}});
test('sparse mapping arrays cannot silently produce undefined port tokens',async()=>{const map=[0,,2];assert.throws(()=>validateMap(map,3),err('MAP'));const a=args(),plan=await createPlan(a);plan.inputMap=map;await assert.rejects(applyPlan({...a,plan}),err('MAP'));});
test('sparse caller and instance arrays reject explicitly',async()=>{const a=args(),plan=await createPlan(a);plan.callers=Array(1);await assert.rejects(applyPlan({...a,plan}),err('PLAN'));const p=await createPlan(a);p.callers[0].instances=Array(1);await assert.rejects(applyPlan({...a,plan:p}),err('SELECTION'));});
test('unescaped comma chaining cannot inject canvas objects through graphical records',()=>{for(const record of ['text 0 0 comment','msg 0 0 message','floatatom 0 0 5 0 0 0 - - -','symbolatom 0 0 5 0 0 0 - - -','listbox 0 0 5 0 0 0 - - -']){assert.throws(()=>parsePatch(head+`#X ${record}, obj 0 10 triplet;\n#X obj 0 30 triplet;\n#X connect 1 0 1 0;\n`),err('RECORD'));}});
test('unescaped comma chaining cannot inject a connection through text',()=>assert.throws(()=>parsePatch(head+'#X obj 0 0 triplet;\n#X text 0 20 comment, connect 0 0 0 0;\n'),err('RECORD')));
test('message and text width metadata is supported without creating extra objects',()=>{const p=parsePatch(head+'#X text 0 0 escaped \\, comma, f 15;\n#X msg 0 40 text, f 20;\n#X obj 0 70 triplet;\n#X connect 1 0 2 0;\n');assert.equal(p.root.objects.length,3);});
test('graphical coordinates reject signed-short overflow that would change native port order',()=>{for(const n of ['32768','40000','-32769','1.5'])assert.throws(()=>inspectPorts(head+`#X obj ${n} 0 inlet;\n#X obj 0 30 inlet;\n`),err('COORDINATE'));assert.deepEqual(inspectPorts(head+'#X obj -32768 0 inlet;\n#X obj 32767 0 inlet;\n').inputs.map(p=>p.x),[-32768,32767]);});
test('restore and text coordinates obey native signed-short limits',()=>{assert.throws(()=>parsePatch(head+'#N canvas 0 0 10 10 inner 0;\n#X restore 40000 0 pd inner;\n'),err('COORDINATE'));assert.throws(()=>parsePatch(head+'#X text 0 -40000 content;\n'),err('COORDINATE'));});
test('oversized atoms including numeric leading zeros and UTF-8 are rejected',()=>{for(const atom of ['0'.repeat(1000),'あ'.repeat(334)])assert.throws(()=>parsePatch(head+`#X text 0 0 ${atom};\n`),err('ATOM'));assert.throws(()=>parsePatch(head+`#X obj ${'0'.repeat(1001)} 0 inlet;\n`),err('ATOM'));assert.equal(parsePatch(head+`#X text 0 0 ${'a'.repeat(999)};\n`).root.objects.length,1);});
test('escaped and dollar-parameterized class aliases are refused rather than ignored',()=>{for(const name of ['in\\let','in\\\\let','out\\let','trip\\let','\\$1','$1'])assert.throws(()=>parsePatch(head+`#X obj 0 0 ${name};\n`),err('UNSUPPORTED'));});
test('connection forward references are rejected in record execution order',()=>assert.throws(()=>parsePatch(head+'#X connect 0 0 1 0;\n#X obj 0 0 triplet;\n#X obj 0 30 triplet;\n'),err('INDEX')));
