/* Event/state regression harness only. Actual layout/browser checks live in browser.mjs. */
import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
import * as core from '../src/core.mjs';import {zipFiles} from '../src/zip.mjs';import {DEMO} from '../web/demo-data.mjs';
const source=(await readFile(new URL('../web/app.mjs',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');
function boot(){
 const elements=new Map();class Element{constructor(tag){this.tagName=tag;this.style={};this.dataset={};this.listeners={};this.children=[];this.value='';}set id(id){this._id=id;elements.set(id,this);}get id(){return this._id;}addEventListener(name,fn){this.listeners[name]=fn;}setAttribute(name,value){this[name]=value;}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=nodes;}}
 const document={getElementById(id){if(!elements.has(id)){const e=new Element('div');e.id=id;}return elements.get(id);},createElement(tag){return new Element(tag);},querySelectorAll(){return[];},documentElement:{}};
 const context=vm.createContext({...core,zipFiles,DEMO,document,TextEncoder,TextDecoder,structuredClone,Option:class extends Element{constructor(text,value){super('option');this.textContent=text;this.value=value;}},setTimeout,Blob,URL});
 vm.runInContext(source+'\n;globalThis.qa={snapshot:()=>({reading,working,revision,savedPlan:!!state.savedPlan,old:state.oldModule,new:state.newModule,reviewDisabled:$("review").disabled,exportDisabled:$("export").disabled}),state:()=>state};',context);
 return{elements,qa:context.qa,change:(id,file)=>elements.get(id).listeners.change({target:{files:[file]}}),click:id=>elements.get(id).listeners.click()};
}
function pendingFile(name,text,method='arrayBuffer'){let release;const wait=new Promise(resolve=>release=resolve);const bytes=new TextEncoder().encode(text);return{file:{name,size:bytes.length,[method]:()=>wait},release:()=>release(method==='text'?text:bytes.buffer)};}
test('new mapping cancels a pending contract read without stranding loading state',async()=>{const app=boot(),p=pendingFile('migration.json','{}','text'),job=app.change('planFile',p.file);assert.equal(app.qa.snapshot().reading,true);app.click('newMapping');assert.equal(app.qa.snapshot().reading,false);assert.equal(app.qa.snapshot().reviewDisabled,false);p.release();await job;assert.equal(app.qa.snapshot().savedPlan,false);assert.equal(app.qa.snapshot().reviewDisabled,false);});
test('independent old and revised source reads both survive reverse completion',async()=>{const app=boot(),a=pendingFile('triplet.pd',DEMO.oldModule.text),b=pendingFile('triplet.pd',DEMO.newModule.text),ja=app.change('oldFile',a.file),jb=app.change('newFile',b.file);b.release();await jb;assert.equal(app.qa.snapshot().reading,true);assert.equal(app.qa.snapshot().new.text,DEMO.newModule.text);a.release();await ja;assert.equal(app.qa.snapshot().reading,false);assert.equal(app.qa.snapshot().old.text,DEMO.oldModule.text);assert.equal(app.qa.snapshot().new.text,DEMO.newModule.text);assert.equal(app.qa.snapshot().reviewDisabled,false);});
test('latest same-field read wins and older completion cannot overwrite it',async()=>{const app=boot(),a=pendingFile('triplet.pd',DEMO.oldModule.text+'#X text 0 0 OUTDATED;\n'),b=pendingFile('triplet.pd',DEMO.oldModule.text),ja=app.change('oldFile',a.file),jb=app.change('oldFile',b.file);b.release();await jb;assert.equal(app.qa.snapshot().reading,false);assert.equal(app.qa.snapshot().old.text,DEMO.oldModule.text);a.release();await ja;assert.equal(app.qa.snapshot().old.text,DEMO.oldModule.text);assert.equal(app.qa.snapshot().reviewDisabled,false);});
test('mapping controls are disabled during a pending contract read',async()=>{const app=boot(),p=pendingFile('migration.json','{}','text'),job=app.change('planFile',p.file);for(const key of ['inputMap-0','inputMap-1','inputMap-2','outputMap-0','outputMap-1'])assert.equal(app.elements.get(key).disabled,true);app.click('newMapping');for(const key of ['inputMap-0','inputMap-1','inputMap-2','outputMap-0','outputMap-1'])assert.equal(app.elements.get(key).disabled,false);p.release();await job;});
test('reset cancels every pending source read',async()=>{const app=boot(),a=pendingFile('triplet.pd',DEMO.oldModule.text),b=pendingFile('triplet.pd',DEMO.newModule.text),ja=app.change('oldFile',a.file),jb=app.change('newFile',b.file);app.click('reset');a.release();b.release();await Promise.all([ja,jb]);assert.equal(app.qa.snapshot().old,null);assert.equal(app.qa.snapshot().new,null);assert.equal(app.qa.snapshot().reading,false);assert.equal(app.qa.snapshot().reviewDisabled,true);});
